Fix reference to bastion security group id
From TF:

```
Error: Error running plan: 1 error(s) occurred:

* module.platform-kops-peering.module.kops.output.bastion_security_group_id: Resource 'data.aws_security_group.bastion' does not have attribute 'ids' for variable 'data.aws_security_group.bastion.*.ids'
```